project_id = "injvwmsqinrcthgdlvux"

[functions.ask-medgemma]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.generate-summary]
verify_jwt = false

[functions.europe-pmc-search]
verify_jwt = false