project_id = "injvwmsqinrcthgdlvux"

[functions.ask-medgemma]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.generate-summary]
verify_jwt = false

[functions.pubmed-search]
verify_jwt = false

[functions.export-history]
verify_jwt = true
